"""
SPECTER Phase 01 Proof of Concept
=================================

Systematic Priority Engine for Cloud Threat Evidence Reconstruction.

Takes multi-source cloud evidence (CloudTrail events and GuardDuty
findings) and returns a sequenced, prioritized, MITRE ATT&CK-mapped
investigation plan generated by Claude on Amazon Bedrock.

The problem this addresses: when responders enter an unfamiliar cloud
environment under time pressure, the sequencing question -- where do we
start, and in what order -- is answered by whoever happens to be the
most experienced analyst available. That does not scale. SPECTER aims to
produce a defensible starting plan from the evidence itself.

This module is the Phase 01 proof of concept. It establishes the core
reasoning path end to end against a fixed evidence set. It is not a
production tool; see "Scope and limitations" in README.md.

Requirements
------------
- An AWS account with Bedrock model access enabled for an Anthropic
  Claude model. Structured tool output requires Claude Sonnet 4.5 or
  later.
- AWS credentials with bedrock:InvokeModel and bedrock:Converse.
- boto3.

Usage
-----
    python specter_poc.py
"""

import json
import sys
from pathlib import Path

import boto3
from botocore.exceptions import ClientError, NoCredentialsError

# Model availability and identifiers vary by account and region. Verify
# with: aws bedrock list-foundation-models --by-provider anthropic
MODEL_ID = "anthropic.claude-sonnet-4-5-20250929-v1:0"
AWS_REGION = "us-gov-west-1"

DATA_DIR = Path(__file__).parent / "synthetic_data"
CLOUDTRAIL_FILE = DATA_DIR / "cloudtrail_events.json"
GUARDDUTY_FILE = DATA_DIR / "guardduty_findings.json"
OUTPUT_FILE = Path(__file__).parent / "investigation_plan_output.json"

SYSTEM_PROMPT = """You are SPECTER, an investigation plan generator for \
cloud forensics analysts. Given raw CloudTrail events and GuardDuty \
findings from a cloud environment under investigation, produce a \
sequenced, prioritized investigation plan.

For each step:
- Map it to a MITRE ATT&CK for Cloud technique ID and name where one applies.
- Explain briefly why it matters (rationale).
- Note which evidence sources support it.
- Assign a priority of critical, high, medium, or low based on how much \
it would change the investigation's direction if confirmed.

Sequence steps in the order an analyst should pursue them, not the order \
events occurred in. Call out any logging gaps or evidence that appears to \
be missing or incomplete. Use the submit_investigation_plan tool to \
return your answer; do not respond in plain text."""

# A tool schema is used rather than free-text parsing so the model's
# output is constrained to a known structure and can be consumed
# programmatically by downstream components.
TOOL_CONFIG = {
    "tools": [{
        "toolSpec": {
            "name": "submit_investigation_plan",
            "description": "Submit the completed cloud forensics investigation plan.",
            "inputSchema": {"json": {
                "type": "object",
                "properties": {
                    "environment_summary": {
                        "type": "string",
                        "description": "One or two sentence summary of what appears to have happened."
                    },
                    "forensic_readiness_notes": {
                        "type": "string",
                        "description": "Notes on evidence gaps, logging coverage, or retention concerns."
                    },
                    "key_hypotheses": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Leading theories of what occurred, to confirm or rule out."
                    },
                    "investigation_plan": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "step": {"type": "integer"},
                                "priority": {
                                    "type": "string",
                                    "enum": ["critical", "high", "medium", "low"]
                                },
                                "action": {"type": "string"},
                                "rationale": {"type": "string"},
                                "attack_technique_id": {"type": "string"},
                                "attack_technique_name": {"type": "string"},
                                "evidence_sources": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                }
                            },
                            "required": ["step", "priority", "action"]
                        }
                    }
                },
                "required": ["investigation_plan", "key_hypotheses"]
            }}
        }
    }],
    "toolChoice": {"tool": {"name": "submit_investigation_plan"}}
}


def load_evidence():
    """Load the evidence set from the synthetic_data directory.

    Returns:
        tuple: (cloudtrail_events, guardduty_findings) as lists of dicts.
    """
    cloudtrail = json.loads(CLOUDTRAIL_FILE.read_text())
    guardduty = json.loads(GUARDDUTY_FILE.read_text())
    return cloudtrail, guardduty


def build_messages(cloudtrail, guardduty):
    """Assemble the evidence into a Bedrock Converse message payload.

    Phase 01 passes the full evidence set in a single message. See
    "Scope and limitations" in README.md for why this does not hold at
    production log volume.

    Args:
        cloudtrail: List of CloudTrail event records.
        guardduty: List of GuardDuty finding records.

    Returns:
        list: Messages array formatted for the Converse API.
    """
    evidence_text = (
        f"CLOUDTRAIL EVENTS ({len(cloudtrail)} records):\n"
        f"{json.dumps(cloudtrail, indent=2)}\n\n"
        f"GUARDDUTY FINDINGS ({len(guardduty)} records):\n"
        f"{json.dumps(guardduty, indent=2)}"
    )
    return [{"role": "user", "content": [{"text": evidence_text}]}]


def call_specter(client, messages):
    """Invoke the model and extract the structured plan from the response.

    Args:
        client: A boto3 bedrock-runtime client.
        messages: Messages array from build_messages().

    Returns:
        dict: The investigation plan matching the tool input schema.

    Raises:
        RuntimeError: If the model returns no tool call.
    """
    response = client.converse(
        modelId=MODEL_ID,
        system=[{"text": SYSTEM_PROMPT}],
        messages=messages,
        toolConfig=TOOL_CONFIG,
        inferenceConfig={"temperature": 0.2, "maxTokens": 4096},
    )
    for block in response["output"]["message"]["content"]:
        if "toolUse" in block:
            return block["toolUse"]["input"]
    raise RuntimeError(
        "Model did not return a tool call. Raw response:\n"
        + json.dumps(response, indent=2, default=str)
    )


def print_plan(plan):
    """Render the investigation plan to stdout.

    Args:
        plan: Investigation plan dict from call_specter().
    """
    print("\n" + "=" * 70)
    print("SPECTER INVESTIGATION PLAN")
    print("=" * 70)
    print(f"\nEnvironment summary: {plan.get('environment_summary', 'n/a')}")
    print(f"\nForensic readiness notes: {plan.get('forensic_readiness_notes', 'n/a')}")

    print("\nKey hypotheses:")
    for hypothesis in plan.get("key_hypotheses", []):
        print(f"  - {hypothesis}")

    print("\nSequenced plan:")
    for step in plan.get("investigation_plan", []):
        priority = step.get("priority", "?").upper()
        print(f"\n  [{priority}] Step {step.get('step', '?')}: {step.get('action', '')}")
        if step.get("attack_technique_id"):
            print(f"      ATT&CK: {step['attack_technique_id']} - {step.get('attack_technique_name', '')}")
        if step.get("rationale"):
            print(f"      Why: {step['rationale']}")
        if step.get("evidence_sources"):
            print(f"      Evidence: {', '.join(step['evidence_sources'])}")

    print("\n" + "=" * 70)


def main():
    if not CLOUDTRAIL_FILE.exists() or not GUARDDUTY_FILE.exists():
        sys.exit(f"Evidence files not found. Expected them in {DATA_DIR}")

    cloudtrail, guardduty = load_evidence()
    messages = build_messages(cloudtrail, guardduty)

    try:
        client = boto3.client("bedrock-runtime", region_name=AWS_REGION)
        plan = call_specter(client, messages)
    except NoCredentialsError:
        sys.exit("No AWS credentials found. Configure credentials and retry.")
    except ClientError as error:
        code = error.response.get("Error", {}).get("Code", "")
        if code in ("AccessDeniedException", "ValidationException"):
            sys.exit(
                f"Bedrock call failed ({code}).\n"
                f"Common causes: model access is not enabled for {MODEL_ID} "
                f"in {AWS_REGION}, or the model identifier has changed.\n"
                f"Verify with:\n"
                f"  aws bedrock list-foundation-models --by-provider anthropic "
                f"--region {AWS_REGION}\n"
                f"then update MODEL_ID."
            )
        raise

    print_plan(plan)
    OUTPUT_FILE.write_text(json.dumps(plan, indent=2))
    print(f"\nPlan written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
